---
version: '3'
services:
  psql:
    image: jutonz/homepage-dev-psql:6
    volumes:
    - "../../:/tmp/code"
    - pgdata:/var/lib/postgresql/data
  redis:
    image: jutonz/homepage-dev-redis:1
  app:
    image: jutonz/homepage-dev-app:30
    environment:
    - SECRET_KEY_BASE="9Z4EOxi6xe+P7ci7gSQn/Lqt4QIXinGJu+CW4YI0lQYaBzFfJsvLvMDm2B38ETM+"
    - CI
    stdin_open: true
    tty: true
    volumes:
    - ci_code:/tmp/ciapp
    ports:
    - 4000:4000
    depends_on:
    - psql
    - redis
    links:
    - psql
    - redis
    working_dir: "/app"
volumes:
  pgdata: 
  ci_code: 
