- match:
    dependency_name: "autoprefixer"
    update_type: semver:minor
- match:
    dependency_name: "@types/node"
    update_type: semver:minor
- match:
    dependency_name: "@types/react"
    update_type: semver:minor
- match:
    dependency_name: "@playwright/test"
    update_type: semver:minor
- match:
    dependency_name: "@tailwindcss/postcss"
    update_type: semver:minor
- match:
    dependency_name: "cypress"
    update_type: semver:minor
- match:
    dependency_name: "@fontsource/roboto"
    update_type: semver:minor
- match:
    dependency_name: "prettier"
    update_type: semver:minor
- match:
    dependency_name: "typescript"
    update_type: semver:patch
- match:
    dependency_name: "tailwindcss"
    update_type: semver:patch
