- match:
    dependency_name: "@types/node"
    update_type: semver:minor
- match:
    dependency_name: "@types/react"
    update_type: semver:minor
- match:
    dependency_name: "@playwright/test"
    update_type: semver:minor
- match:
    dependency_name: "cypress"
    update_type: semver:minor
