version: 2
updates:
- package-ecosystem: npm
  directory: "/apps/client/assets"
  schedule:
    interval: daily
    time: "03:00"
    timezone: America/New_York
  open-pull-requests-limit: 10
  groups:
    mui_material:
      patterns:
      - "@mui/material"
      - "@mui/icons-material"
    react:
      patterns:
      - "@types/react"
      - "react"
      - "react-dom"
- package-ecosystem: mix
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
    timezone: America/New_York
  open-pull-requests-limit: 10
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
    timezone: America/New_York
  open-pull-requests-limit: 10
