---
pipeline:
  build-test-image:
    image: docker
    commands:
    - docker build -f docker/ci/testimage/Dockerfile -t jutonz/homepage-ci-testimage:latest. .
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  build-local-dev-psql:
    image: jutonz/homepage-ci-testimage
    pull: false
    group: build
    commands:
    - apk add alpine-sdk ruby ruby-dev --no-cache
    - gem install bigdecimal dctl_rb --no-document
    - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
    - dctl pull psql
    - dctl build psql
    secrets: [ DOCKER_USERNAME, DOCKER_PASSWORD ]
    environment:
    - DOCKER_USERNAME=$$DOCKER_USERNAME
    - DOCKER_PASSWORD=$$DOCKER_PASSWORD
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  build-local-dev-app:
    image: docker
    group: build
    commands:
    - apk add alpine-sdk ruby ruby-dev --no-cache
    - gem install bigdecimal dctl_rb --no-document
    - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
    - ls -alh
    - dctl pull app
    - dctl build app
    secrets: [ DOCKER_USERNAME, DOCKER_PASSWORD ]
    environment:
    - DOCKER_USERNAME=$$DOCKER_USERNAME
    - DOCKER_PASSWORD=$$DOCKER_PASSWORD
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  build-local-dev-redis:
    image: docker
    group: build
    commands:
    - apk add alpine-sdk ruby ruby-dev --no-cache
    - gem install bigdecimal dctl_rb --no-document
    - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
    - dctl pull redis
    - dctl build redis
    secrets: [ DOCKER_USERNAME, DOCKER_PASSWORD ]
    environment:
    - DOCKER_USERNAME=$$DOCKER_USERNAME
    - DOCKER_PASSWORD=$$DOCKER_PASSWORD
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  initdb:
    image: docker
    commands:
    - apk add alpine-sdk ruby ruby-dev --no-cache
    - gem install bigdecimal dctl_rb --no-document
    - apk add py-pip --no-cache
    - pip install docker-compose
    - dctl run app "mix deps.get"
    - dctl initdb
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  unit-tests:
    group: test
    image: docker
    commands:
    - apk add alpine-sdk ruby ruby-dev --no-cache
    - gem install bigdecimal dctl_rb --no-document
    - apk add py-pip --no-cache
    - pip install docker-compose
    - dctl run app /etc/runtests.sh
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
