---
pipeline:
  build-test-image:
    image: docker
    commands:
    - docker login -u "$PRIVATE_DOCKER_USERNAME" -p "$PRIVATE_DOCKER_PASSWORD" https://registry.jutonz.com
    - docker build --pull=true -f docker/ci/testimage/Dockerfile -t registry.jutonz.com/jutonz/homepage-ci-testimage:latest .
    secrets: [ PRIVATE_DOCKER_USERNAME, PRIVATE_DOCKER_PASSWORD ]
    environment:
    - PRIVATE_DOCKER_USERNAME=$$PRIVATE_DOCKER_USERNAME
    - PRIVATE_DOCKER_PASSWORD=$$PRIVATE_DOCKER_PASSWORD
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  build-local-dev-psql:
    image: registry.jutonz.com/jutonz/homepage-ci-testimage
    group: build
    commands:
    - dctl build psql
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  build-local-dev-app:
    image: registry.jutonz.com/jutonz/homepage-ci-testimage
    group: build
    commands:
    - dctl build app
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  build-local-dev-redis:
    image: registry.jutonz.com/jutonz/homepage-ci-testimage
    group: build
    commands:
    - dctl build redis
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  initdb:
    image: registry.jutonz.com/jutonz/homepage-ci-testimage
    commands:
    - ls -alh
    - dctl run psql /etc/initdb.sh
    - docker run -v dev_code:/data --name helper busybox true
    - docker cp . helper:/data
    - docker rm helper
    - dctl run app /etc/seedci.sh
    environment:
    - DOCKER_HOST=tcp://dind
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  unit-tests:
    group: test
    image: registry.jutonz.com/jutonz/homepage-ci-testimage
    commands:
    - dctl run app /etc/runtests.sh
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  push-dev-app:
    group: push
    image: registry.jutonz.com/jutonz/homepage-ci-testimage
    commands:
    - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
    - dctl push app
    secrets: [ DOCKER_USERNAME, DOCKER_PASSWORD ]
    environment:
    - DOCKER_USERNAME=$$DOCKER_USERNAME
    - DOCKER_PASSWORD=$$DOCKER_PASSWORD
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  cleanup:
    image: registry.jutonz.com/jutonz/homepage-ci-testimage
    commands:
    - dctl rm -f
    - docker volume prune -f
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    when:
      status: [success, failure]
services:
  dind:
    image: docker:dind
    privileged: true
    #command: ["--storage-driver=overlay2", "--tls=false"]
