---
pipeline:
  redis:
    image: plugins/docker
    repo: jutonz/homepage-dev-redis
    dockerfile: docker/dev/redis/Dockerfile
    secrets: [ DOCKER_USERNAME, DOCKER_PASSWORD ]
    pull: true
  psql:
    image: docker
    commands:
    - docker login -u "$DOCKER_LOGIN" -p "$DOCKER_PASSWORD"
    - docker build -t jutonz/homepage-dev-psql .
    - docker push jutonz/homepage-dev-psql
    secrets: [ DOCKER_USERNAME, DOCKER_PASSWORD ]
    environment:
    - DOCKER_LOGIN=$$DOCKER_LOGIN
    - DOCKER_PASSWORD=$$DOCKER_PASSWORD
    #- DOCKER_HOST=tcp://0.0.0.0:2375
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  #psql:
    #image: plugins/docker
    #repo: jutonz/homepage-dev-psql
    #dockerfile: docker/dev/psql/Dockerfile
    #secrets: [ DOCKER_USERNAME, DOCKER_PASSWORD ]
    #pull: true
  #app:
    #image: plugins/docker
    #repo: jutonz/homepage-dev-app
    #dockerfile: docker/dev/app/Dockerfile
    #secrets: [ DOCKER_USERNAME, DOCKER_PASSWORD ]
    #pull: true
    #pull-image: true

#services:
  #docker:
    #image: docker:dind
    #command: [ "--storage-driver=overlay2", "--tls=false" ]
    #privileged: true
