---
pipeline:
  build-test-image:
    image: docker
    commands:
    - docker login -u "$PRIVATE_DOCKER_USERNAME" -p "$PRIVATE_DOCKER_PASSWORD" https://registry.jutonz.com
    - docker build --pull=true -f docker/ci/testimage/Dockerfile -t registry.jutonz.com/jutonz/homepage-ci-testimage:latest .
    secrets: [ PRIVATE_DOCKER_USERNAME, PRIVATE_DOCKER_PASSWORD ]
    environment:
    - PRIVATE_DOCKER_USERNAME=$$PRIVATE_DOCKER_USERNAME
    - PRIVATE_DOCKER_PASSWORD=$$PRIVATE_DOCKER_PASSWORD
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  build-local-dev-psql:
    image: registry.jutonz.com/jutonz/homepage-ci-testimage
    group: build
    commands:
    - dctl build psql
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  build-local-dev-app:
    image: registry.jutonz.com/jutonz/homepage-ci-testimage
    group: build
    commands:
    - dctl build app
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  build-local-dev-redis:
    image: registry.jutonz.com/jutonz/homepage-ci-testimage
    group: build
    commands:
    - dctl build redis
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  initdb:
    image: registry.jutonz.com/jutonz/homepage-ci-testimage
    commands:
    - apk add alpine-sdk ruby ruby-dev --no-cache
    - gem install bigdecimal dctl_rb --no-document
    - apk add py-pip --no-cache
    - pip install docker-compose
    - dctl run app /etc/fetchdeps.sh
    - dctl initdb
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  unit-tests:
    group: test
    image: docker
    commands:
    - apk add alpine-sdk ruby ruby-dev --no-cache
    - gem install bigdecimal dctl_rb --no-document
    - apk add py-pip --no-cache
    - pip install docker-compose
    - dctl run app /etc/runtests.sh
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
