---
pipeline:
  build-test-image:
    image: docker
    commands:
    - docker login -u "$PRIVATE_DOCKER_USERNAME" -p "$PRIVATE_DOCKER_PASSWORD" https://registry.jutonz.com
    - docker pull $IMAGE:latest
    - docker build --cache-from $IMAGE:latest -f docker/ci/testimage/Dockerfile -t $IMAGE:$TAG .
    - docker tag $IMAGE:$TAG $IMAGE:latest
    - docker push $IMAGE:$TAG
    secrets: [ PRIVATE_DOCKER_USERNAME, PRIVATE_DOCKER_PASSWORD ]
    environment:
    - PRIVATE_DOCKER_USERNAME=$$PRIVATE_DOCKER_USERNAME
    - PRIVATE_DOCKER_PASSWORD=$$PRIVATE_DOCKER_PASSWORD
    - DOCKER_HOST=tcp://dind:2375
    - IMAGE=registry.jutonz.com/jutonz/homepage-ci-testimage
    - TAG=4
  build-local-dev-psql:
    image: registry.jutonz.com/jutonz/homepage-ci-testimage:4
    group: build
    commands:
    - dctl version
    - dctl pull psql
    - dctl build psql --cache-from=`dctl tag-for psql`
    environment:
    - DOCKER_HOST=tcp://dind:2375
  build-local-dev-app:
    image: registry.jutonz.com/jutonz/homepage-ci-testimage:4
    group: build
    commands:
    - dctl pull app
    - dctl build app --cache-from=`dctl tag-for app` --pull=false
    environment:
    - DOCKER_HOST=tcp://dind:2375
  build-local-dev-redis:
    image: registry.jutonz.com/jutonz/homepage-ci-testimage:4
    group: build
    commands:
    - dctl build redis --cache-from=`dctl tag-for redis` --pull=true
    environment:
    - DOCKER_HOST=tcp://dind:2375
  initdb:
    image: registry.jutonz.com/jutonz/homepage-ci-testimage:4
    commands:
    - docker --host=$DOCKER_HOST run -v dev_code:/data --name helper busybox true
    - docker --host=$DOCKER_HOST cp . helper:/data
    - docker --host=$DOCKER_HOST rm helper
    #- docker-compose -f docker/dev/docker-compose.yml run app /etc/initdb.sh
    - dctl run psql /etc/initdb.sh --host=$DOCKER_HOST
    - dctl run app /etc/seedci.sh --host=$DOCKER_HOST
    environment:
    - DOCKER_HOST=tcp://dind:2375
  unit-tests:
    group: test
    image: registry.jutonz.com/jutonz/homepage-ci-testimage:4
    commands:
    - dctl run app /etc/runtests.sh
    environment:
    - DOCKER_HOST=tcp://dind:2375
  push-dev-app:
    group: push
    image: registry.jutonz.com/jutonz/homepage-ci-testimage:4
    commands:
    - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
    - dctl push app
    secrets: [ DOCKER_USERNAME, DOCKER_PASSWORD ]
    environment:
    - DOCKER_USERNAME=$$DOCKER_USERNAME
    - DOCKER_PASSWORD=$$DOCKER_PASSWORD
    environment:
    - DOCKER_HOST=tcp://dind:2375
  cleanup:
    image: registry.jutonz.com/jutonz/homepage-ci-testimage:4
    commands:
    - dctl rm -f
    - docker volume prune -f
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    when:
      status: [success, failure]
services:
  dind:
    image: docker:dind
    privileged: true
    #command: ["--storage-driver=overlay2", "--tls=false"]
