#!/bin/bash

set -ex

cd /app

# wait for a moment for the psql container to come up
max_tries=20
tries=0
found=0
domain=psql

while [ $found -eq 0 ] && [ $tries -lt $max_tries ]; do
  tries=$((tries + 1))

  echo "ping $tries"
  if ping $domain -c1 > /dev/null; then
    echo "found!"
    found=1
  else
    sleep 1
  fi
done

mix do ecto.create --force, ecto.migrate &
MIX_ENV=test mix do ecto.drop, ecto.create --force, ecto.migrate &
wait
