#!/bin/bash

################################################################################
# This is run each time the app container is started. Mostly it ensures that
# required dependencies are present.
################################################################################

set -ex

if [ -n "$CI" ]; then
  cd /tmp/ciapp
else
  cd /app
fi

mix deps.get
