use Mix.Config

# For production, we often load configuration from external sources, such as
# your system environment. For this reason, you won't find the :http
# configuration below, but set inside ClientWeb.Endpoint.init/2 when
# load_from_system_env is true. Any dynamic configuration should be done there.
#
# Don't forget to configure the url host to something meaningful, Phoenix uses
# this information when generating URLs.
#
# Finally, we also include the path to a cache manifest containing the digested
# version of static files. This manifest is generated by the mix phx.digest
# task which you typically run after static files are built.

port = System.get_env("PORT") || "4000" |> String.to_integer()

config :client, ClientWeb.Endpoint,
  http: [port: port],
  url: [host: "jutonz.com", scheme: "http"],
  cache_static_manifest: "priv/static/cache_manifest.json"

# Do not print debug messages in production
config :logger, level: :info

config :client, Client.Mailer,
  adapter: Bamboo.SendGridAdapter,
  api_key: {:system, "SENDGRID_API_KEY"}

db_url = System.get_env("DATABASE_URL")
db_pool_size = System.get_env("POOL_SIZE") || "10" |> String.to_integer()

config :client, Client.Repo,
  adapter: Ecto.Adapters.Postgres,
  url: db_url,
  pool_size: db_pool_size,
  ssl: true

config :sentry,
  dsn: {:system, "SENTRY_DSN"},
  environment_name: :prod,
  enable_source_code_context: true,
  root_source_code_path: File.cwd!(),
  tags: %{
    env: "production"
  },
  included_environments: [:prod]
