use Mix.Config

# For production, we often load configuration from external sources, such as
# your system environment. For this reason, you won't find the :http
# configuration below, but set inside ClientWeb.Endpoint.init/2 when
# load_from_system_env is true. Any dynamic configuration should be done there.
#
# Don't forget to configure the url host to something meaningful, Phoenix uses
# this information when generating URLs.
#
# Finally, we also include the path to a cache manifest containing the digested
# version of static files. This manifest is generated by the mix phx.digest
# task which you typically run after static files are built.

config :client, ClientWeb.Endpoint,
  http: [port: 4000],
  url: [host: "jutonz.com", scheme: "http"],
  cache_static_manifest: "priv/static/cache_manifest.json"

# Do not print debug messages in production
config :logger, level: :info

# Configures the database
db_host = System.get_env("PGHOST") || "psql"
db_user = System.get_env("PGUSER")
db_pass = System.get_env("PGPASS")
db_port = System.get_env("PGPORT") || 5432

config :client, Client.Repo,
  adapter: Ecto.Adapters.Postgres,
  hostname: db_host,
  username: db_user,
  password: db_pass,
  port: db_port,
  database: "homepage_prod",
  pool_size: 20
