apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: app
  namespace: homepage
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - image: jutonz/homepage-prod-app:95
        name: app
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /api/healthz
            port: 4000
            scheme: HTTP
          initialDelaySeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /api/healthz
            port: 4000
            scheme: HTTP
          initialDelaySeconds: 10
          timeoutSeconds: 5
        env:
          - name: SECRET_KEY_BASE
            valueFrom:
              secretKeyRef:
                name: secret-key-base
                key: SECRET_KEY_BASE
          - name: TWITCH_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: twitch
                key: TWITCH_CLIENT_ID
          - name: TWITCH_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: twitch
                key: TWITCH_CLIENT_SECRET
          - name: TWITCH_REDIRECT_URI
            valueFrom:
              secretKeyRef:
                name: twitch
                key: TWITCH_REDIRECT_URI
          - name: DB_HOST
            value: psql
          - name: DB_PORT
            value: "5432"
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: dbsecrets
                key: DB_USER
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                name: dbsecrets
                key: DB_PASS
          - name: DB_POOL_SIZE
            value: "20"
      restartPolicy: Always
