apiVersion: batch/v1
kind: Job
metadata:
  name: psql-backup-oneoff
  namespace: homepage
spec:
  template:
    metadata:
      name: psql-backup-oneoff
    spec:
      containers:
      - name: homepage-db-backup
        image: jutonz/homepage-prod-psql:10
        args:
        - /bin/bash
        - /etc/backup.sh
        env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: dbsecrets
                key: PGUSER
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: dbsecrets
                key: PGPASS
          - name: POSTGRES_DB
            value: homepage_prod
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: aws
                key: AWS_ACCESS_KEY_ID
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: aws
                key: AWS_SECRET_ACCESS_KEY
      - name: twitch-db-backup
        image: jutonz/homepage-prod-psql:10
        args:
        - /bin/bash
        - /etc/backup.sh
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: dbsecrets
              key: PGUSER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: dbsecrets
              key: PGPASS
        - name: POSTGRES_DB
          value: homepage_twitch_prod
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws
              key: AWS_SECRET_ACCESS_KEY
      restartPolicy: Never
