name: Elixir CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  get_deps:
    name: mix deps.get
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Elixir
      uses: erlef/setup-elixir@885971a72ed1f9240973bd92ab57af8c1aa68f24
      with:
        elixir-version: '1.10.3'
        otp-version: '23.0'
    - name: Restore dependencies cache
      uses: actions/cache@v2
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-
    - run: mix deps.get


  yarn_install:
    name: yarn install
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: 12.17
    - name: Restore node_modules cache
      uses: actions/cache@v2
      with:
        path: deps
        key: ${{ runner.os }}-node-modules-${{ hashFiles('.tool-versions') }}-${{ hashFiles('apps/client/assets/yarn.lock') }}
        restore-keys: ${{ runner.os }}-node-modules-
    - name: yarn install
      working-directory: apps/client/assets
      run: yarn install

  build:
    name: mix format
    needs: get_deps
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Elixir
      uses: erlef/setup-elixir@885971a72ed1f9240973bd92ab57af8c1aa68f24
      with:
        elixir-version: '1.10.3'
        otp-version: '23.0'
    - name: Restore dependencies cache
      uses: actions/cache@v2
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-
    - run: mix format --check-formatted
