name: Elixir CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_dev:
    name: mix compile and dialyzer
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Elixir
      uses: erlef/setup-elixir@885971a72ed1f9240973bd92ab57af8c1aa68f24
      with:
        elixir-version: '1.12.2'
        otp-version: '24.0'
    - name: Restore dev cache
      uses: actions/cache@v2
      with:
        path: |
          deps
          _build/dev
        key: v1-dev-${{ hashFiles('.tool-versions')}}-${{ hashFiles('mix.lock') }}
        restore-keys: v1-dev-
    - name: Restore PLT cache
      uses: actions/cache@v2
      with:
        path: _plts
        key: v1-plts-${{ hashFiles('.tool-versions') }}-${{ hashFiles('mix.lock') }}
        restore-keys: |
          v1-plts-${{ hashFiles('.tool-versions') }}-${{ hashFiles('mix.lock') }}
          v1-plts-${{ hashFiles('.tool-versions') }}-
          v1-plts-
    - run: mix format --check-formatted
    - run: mix deps.get
    - run: mix compile --warnings-as-errors
    - run: mix dialyzer

  yarn_install:
    name: yarn install and bundle
    runs-on: ubuntu-latest
    env:
      MIX_ENV: prod
    steps:
    - uses: actions/checkout@v2
    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: 12.22
    - name: Restore node_modules cache
      uses: actions/cache@v2
      with:
        path: apps/client/assets/node_modules
        key: v1-node-modules-${{ hashFiles('.tool-versions') }}-${{ hashFiles('apps/client/assets/yarn.lock') }}
        restore-keys: |
          v1-node-modules-${{ hashFiles('.tool-versions') }}-${{ hashFiles('apps/client/assets/yarn.lock') }}
          v1-node-modules-${{ hashFiles('.tool-versions') }}
          v1-node-modules-
    - name: Restore yarn cache
      uses: actions/cache@v2
      with:
        path: ~/.cache/yarn
        key: v1-yarn-${{ hashFiles('.tool-versions') }}-${{ hashFiles('apps/client/assets/yarn.lock') }}
        restore-keys: |
          v1-yarn-${{ hashFiles('.tool-versions') }}-${{ hashFiles('apps/client/assets/yarn.lock') }}
          v1-yarn-${{ hashFiles('.tool-versions') }}
          v1-yarn-
    - name: Restore static asset cache
      uses: actions/cache@v2
      with:
        path: apps/client/priv/static
        key: v3-static-assets-${{ github.ref }}
    - name: yarn install
      working-directory: apps/client/assets
      run: yarn install
    - name: yarn lint
      working-directory: apps/client/assets
      run: yarn lint
    - name: check typings
      working-directory: apps/client/assets
      run: npx tsc --project ./tsconfig.json
    - name: yarn bundle:js
      working-directory: apps/client/assets
      run: yarn bundle:js
    - name: yarn bundle:css
      working-directory: apps/client/assets
      run: yarn bundle:css
    - name: tree
      working-directory: apps/client/priv/static
      run: tree .

  mix_test:
    name: mix test
    needs: yarn_install
    runs-on: ubuntu-latest
    env:
      MIX_ENV: test
      TWITCH_DATASTORE_DISABLED: "true"
    services:
      postgres:
        image: circleci/postgres:12-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_DB: homepage_test
          POSTGRES_PASSWORD:
        ports:
        - 5432:5432
      redis:
        image: circleci/redis
        ports:
        - 6379:6379
    steps:
    - uses: actions/checkout@v2
    - name: Set up Elixir
      uses: erlef/setup-elixir@885971a72ed1f9240973bd92ab57af8c1aa68f24
      with:
        elixir-version: '1.12.2'
        otp-version: '24.0'
    - name: Restore static asset cache
      uses: actions/cache@v2
      with:
        path: apps/client/priv/static
        key: v3-static-assets-${{ github.ref }}
    - name: Restore test cache
      uses: actions/cache@v2
      with:
        path: |
          deps
          _build/test
        key: v2-test-${{ hashFiles('.tool-versions') }}-${{ hashFiles('mix.lock') }}
        restore-keys: |
          v2-test-${{ hashFiles('.tool-versions') }}-${{ hashFiles('mix.lock') }}
          v2-test-${{ hashFiles('.tool-versions') }}-
    - run: tree apps/client/priv/static
    - run: mix deps.get
    - run: mix compile --warnings-as-errors
    - run: mix do ecto.create, ecto.migrate
    - run: mix test
