name: Elixir CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  get_deps:
    name: mix deps.get and format
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Elixir
      uses: erlef/setup-elixir@885971a72ed1f9240973bd92ab57af8c1aa68f24
      with:
        elixir-version: '1.10.3'
        otp-version: '23.0'
    - name: Restore dependencies cache
      uses: actions/cache@v2
      with:
        path: deps
        key: v1-mix-${{ hashFiles('.tool-versions') }}-${{ hashFiles('mix.lock') }}
        restore-keys: |
          v1-mix-${{ hashFiles('.tool-versions') }}-${{ hashFiles('mix.lock') }}
          v1-mix-${{ hashFiles('.tool-versions') }}-
    - run: mix format --check-formatted
    - run: mix deps.get

  build_dev:
    name: mix compile and dialyzer
    runs-on: ubuntu-latest
    needs: get_deps
    steps:
    - uses: actions/checkout@v2
    - name: Set up Elixir
      uses: erlef/setup-elixir@885971a72ed1f9240973bd92ab57af8c1aa68f24
      with:
        elixir-version: '1.10.3'
        otp-version: '23.0'
    - name: Restore dependencies cache
      uses: actions/cache@v2
      with:
        path: deps
        key: v1-mix-${{ hashFiles('.tool-versions') }}-${{ hashFiles('mix.lock') }}
        restore-keys: |
          v1-mix-${{ hashFiles('.tool-versions') }}-${{ hashFiles('mix.lock') }}
          v1-mix-${{ hashFiles('.tool-versions') }}-
    - name: Restore dev cache
      uses: actions/cache@v2
      with:
        path: |
          deps
          _build/dev
        key: v1-dev-${{ hashFiles('mix.lock') }}
        restore-keys: v1-dev-
    - name: Restore PLT cache
      uses: actions/cache@v2
      with:
        path: _plts
        key: v1-plts-${{ hashFiles('.tool-versions') }}-${{ hashFiles('mix.lock') }}
        restore-keys: |
          v1-plts-${{ hashFiles('.tool-versions') }}-${{ hashFiles('mix.lock') }}
          v1-plts-${{ hashFiles('.tool-versions') }}-
          v1-plts-
    - run: mix compile --warnings-as-errors
    - run: mix dialyzer

  yarn_install:
    name: yarn install
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: 12.17
    - name: Restore node_modules cache
      uses: actions/cache@v2
      with:
        path: apps/client/assets/node_modules
        key: v1-node-modules-${{ hashFiles('.tool-versions') }}-${{ hashFiles('apps/client/assets/yarn.lock') }}
        restore-keys: |
          v1-node-modules-${{ hashFiles('.tool-versions') }}-${{ hashFiles('apps/client/assets/yarn.lock') }}
          v1-node-modules-${{ hashFiles('.tool-versions') }}
          v1-node-modules-
    - name: Restore yarn cache
      uses: actions/cache@v2
      with:
        path: ~/.cache/yarn
        key: v1-yarn-${{ hashFiles('.tool-versions') }}-${{ hashFiles('apps/client/assets/yarn.lock') }}
        restore-keys: |
          v1-yarn-${{ hashFiles('.tool-versions') }}-${{ hashFiles('apps/client/assets/yarn.lock') }}
          v1-yarn-${{ hashFiles('.tool-versions') }}
          v1-yarn-
    - name: yarn install
      working-directory: apps/client/assets
      run: yarn install
    - name: yarn lint
      working-directory: apps/client/assets
      run: yarn lint

  build_static:
    name: yarn bundle:static
    runs-on: ubuntu-latest
    needs: yarn_install
    steps:
    - uses: actions/checkout@v2
    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: 12.17
    - name: Restore node_modules cache
      uses: actions/cache@v2
      with:
        path: apps/client/assets/node_modules
        key: v1-node-modules-${{ hashFiles('.tool-versions') }}-${{ hashFiles('apps/client/assets/yarn.lock') }}
        restore-keys: |
          v1-node-modules-${{ hashFiles('.tool-versions') }}-${{ hashFiles('apps/client/assets/yarn.lock') }}
          v1-node-modules-${{ hashFiles('.tool-versions') }}
          v1-node-modules-
    - name: Restore static asset cache
      uses: actions/cache@v2
      with:
        path: apps/client/priv/static/js
        key: v1-static-assets-${{ github.ref }}
    - name: yarn bundle:static
      working-directory: apps/client/assets
      run: yarn bundle:static

  build_react:
    name: yarn bundle:react
    runs-on: ubuntu-latest
    needs: yarn_install
    steps:
    - uses: actions/checkout@v2
    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: 12.17
    - name: Restore node_modules cache
      uses: actions/cache@v2
      with:
        path: apps/client/assets/node_modules
        key: v1-node-modules-${{ hashFiles('.tool-versions') }}-${{ hashFiles('apps/client/assets/yarn.lock') }}
        restore-keys: |
          v1-node-modules-${{ hashFiles('.tool-versions') }}-${{ hashFiles('apps/client/assets/yarn.lock') }}
          v1-node-modules-${{ hashFiles('.tool-versions') }}
          v1-node-modules-
    - name: yarn bundle:react
      working-directory: apps/client/assets
      run: yarn bundle:react

  mix_test:
    name: mix test
    needs: [build_dev, build_static]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Elixir
      uses: erlef/setup-elixir@885971a72ed1f9240973bd92ab57af8c1aa68f24
      with:
        elixir-version: '1.10.3'
        otp-version: '23.0'
    - name: Restore dependencies cache
      uses: actions/cache@v2
      with:
        path: deps
        key: v1-mix-${{ hashFiles('.tool-versions') }}-${{ hashFiles('mix.lock') }}
        restore-keys: |
          v1-mix-${{ hashFiles('.tool-versions') }}-${{ hashFiles('mix.lock') }}
          v1-mix-${{ hashFiles('.tool-versions') }}-
    - name: Restore static asset cache
      uses: actions/cache@v2
      with:
        path: apps/client/priv/static/js
        key: v1-static-assets-${{ github.ref }}
    - name: Restore test cache
      uses: actions/cache@v2
      with:
        path: _build/test
        key: v1-test-${{ hashFiles('.tool-versions') }}-${{ hashFiles('mix.lock') }}
        restore-keys: |
          v1-test-${{ hashFiles('.tool-versions') }}-${{ hashFiles('mix.lock') }}
          v1-test-${{ hashFiles('.tool-versions') }}-
    - run: MIX_ENV=test mix compile --warnings-as-errors
    - run: mix test
